### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by emilrowland** [simonstewart/swagger-to-PDF#15]
Would be greate if you could use this software on a yaml file as well.

**Comment by simonstewart** [comment]
Hi Emil,

That's a good idea.

**Comment by emilrowland** [comment]
#16

**Comment by emilrowland** [comment]
I have created support for YAML files now. See pull request #16

**Comment by simonstewart** [comment]
@emilrowland thanks.  This PR is on my TODO list.  
Appreciate the time you took in doing this.

**Comment by emilrowland** [comment]
I have resolved the conflicts now for the pull request.
