### ISSUE TITLE
Could not find phantomjs-pdf

### ISSUE THREAD

**Issue by trigunam** [simonstewart/swagger-to-PDF#5]
Its mentioned that phantomjs-pdf is a dependency but could not find a link or reference to this project.

I really want to use this library to convert my swagger documentation to PDF however its not working for me.

Thanks
Triguna

**Comment by simonstewart** [comment]
Hi Triguna

Thanks for trying it out.

Have you run "npm install" to ensure all dependencies are installed?

**Comment by trigunam** [comment]
Hey
I am using this in Windows machine. Is there any other way?
Thanks
Triguna

**Comment by simonstewart** [comment]
You'll need to have Node installed and then run that npm command.
Don't think there is another reliable way to have the dependency installed.

More than happy to assist over Skype if you like, my user name is SimonMStewart

**Comment by simonstewart** [comment]
Closing this issue as there wasn't any feedback
