### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by kpakur** [simonstewart/swagger-to-PDF#6]
Hi,

I had issues to get this working on windows. What finally helped was a quick fix inside phantom-script.js to add "file://" to the skeleton.html path.
from 
page.open(page.libraryPath + "/skeleton.html", function (status) 
to
page.open("file://" + page.libraryPath + "/skeleton.html", function (status) 

Naturally the best would be to make this fix slightly better to check the platform and then add the "file://" prefix etc., but I just wanted to try it out on windows and this quick change allowed me to get the pdf created.

**Comment by simonstewart** [comment]
Hi.
Perhaps an issue between OSX and Windows?

Thanks for finding it.  Can you do a pull request?

**Comment by kampak1111** [comment]
Hi,

I put in a pull request with some other fixes. 

Anyway I just realised that the issue I mentioned is in fact in phantomjs-pdf in lib/phantom-script.js, line 20. So appologies and I will raise it with phantomjs-pdf team then.

Just in case someone had the same and was getting the test.html file fine but empty output.pdf on windows then changing the line may be a hotfix to get this working.

K.

**Comment by simonstewart** [comment]
Thanks so much for the PR!  I've done the merge.

Are you finding the converter useful?
