### ISSUE TITLE
failure to finish process, error at child_process.js:936

### ISSUE THREAD

**Issue by johnbikes** [simonstewart/swagger-to-PDF#9]
This is a problem with phantom-pdf, but has anyone seen this?

child_process.js:936
  var r = this._handle.spawn(options);
                       ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:936:24)
    at exports.spawn (child_process.js:736:9)
    at Object.exports.execFile (child_process.js:618:15)
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/lib/phantomjs-pdf.js:83:16
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:726:13
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:52:16
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:269:32
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:44:16
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:723:17
    at /home/mpf/swagger-to-PDF/node_modules/phantomjs-pdf/node_modules/async/lib/async.js:167:37

**Comment by johnbikes** [comment]
I thought it might be a good idea to clear out the node modules and reinstall, no issues now!

**Comment by simonstewart** [comment]
Hi @johnnytavo, glad the issue resolved itself!
